dist: xenial
language: ruby
cache: bundler

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0

# Only test master
branches:
  only:
    - master

bundler_args: --jobs 7

before_script:
  - git config --global user.email "ci@traivs-ci.org"
  - git config --global user.name "Travis CI"

script: bundle exec rake
