distro: xenial
language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3

# Only test master
branches:
  only:
    - master

bundler_args: --jobs 7

before_script:
  - git config --global user.email "ci@traivs-ci.org"
  - git config --global user.name "Travis CI"

script: bundle exec rake
